### ISSUE TITLE
Modular DI

### ISSUE THREAD

**Issue by chuannguyen1208** [mehdihadeli/ecommerce-modular-monolith#14]
Hi, I want to isolate the dependency injection between modules, which means that we can have an interface sharing across modules and each module has it own implementation. Do you have any idea ?
For example I have Catalog module which use IRepository and a MongoDbRepository class for using mongo db.
Another module called Order Module also use IRepository and a EfCoreRepositoryClass for using ef core.

I would like to ask you that how can I inject or can I isolate DI for each Module ?

**Comment by mehdihadeli** [comment]
Hi,
This is exactly what I did in this project and each module has its own dependency container.
You can take a look to my code.

**Comment by chuannguyen1208** [comment]
> Hi, This is exactly what I did in this project and each module has its own dependency container. You can take a look to my code.

Thank you for your response. I just check out the code and it works amazing. 
I just tried a fews sample projects and haven't found any one but this.

Thanks again =))

**Comment by chuannguyen1208** [comment]
Looks like it just works with minimal api using gateway, I have tried to use module controllers by adding AddApplicationPart and inject a service using [FromService] in the controller, but it still be the main implementation instead of module service.
I'm not sure if it will work if I get a service from HttpContext.

Do you have any idea or I miss something ?
